### prometheus.yml ###
global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - '/etc/prometheus/alert.rules'

# A scrape configuration for cadvisor:
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - cadvisor:8080
